name: katana Build - Instalação de Pacotes Oxys OS

on:
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    container:
      image: debian:stable

    steps:
      # 1. Configura repositórios
      - name: Configurar fontes e repositórios Non-Free
        run: |
          cat <<EOF > /etc/apt/sources.list
          deb http://deb.debian.org/debian stable main contrib non-free non-free-firmware
          deb http://deb.debian.org/debian-security stable-security main contrib non-free non-free-firmware
          deb http://deb.debian.org/debian stable-updates main contrib non-free non-free-firmware
          EOF
          apt-get update

      # 2. Instalar ferramentas básicas de sistema
      - name: Instalar ferramentas de build
        run: |
          apt-get install -y git wget

      # 3. Clonar o repositório
      - name: Clonar repositório
        run: |
          mkdir -p /build_root
          cd /build_root
          git clone https://github.com/linux-oxy-retro-cyber/ODE-oxy-os-debian-edition.git .

      # 4. Instalação por etapas (Prioridade)
      - name: Instalar pacotes de prioridade
        run: |
          cd /build_root/oxys-pack/packges-beta/prioridade/
          apt-get install -y ./oxys-base.deb && apt-get install -f -y

      # 5. Instalação por etapas (Temas)
      - name: Instalar pacotes de temas
        run: |
          cd /build_root/oxys-pack/packges-beta/temas/
          dpkg -i --force-overwrite ./oxys-base.deb && apt-get install -y

      # 6. Instalação por etapas (Calamares)
      - name: Instalar pacotes do Calamares
        run: |
          cd /build_root/oxys-pack/packges-beta/calamares-temas/
          apt-get install -y ./*.deb || apt-get install -f -y
